Repository thunderbird/thunderbird-accounts, pull requests merged in 2025-04, with the labels that each got.

#72 Upgrade to tb_pulumi 0.0.13
  pulumi/requirements.txt
Labels: enhancement, maintenance

#74 Target the Fargate service when deploying
  .github/workflows/deploy-stage.yml
Labels: bug, ci, infra

#60 Expand the E2E test suite
  README.md
  assets/app/vue/components/AccountInfoForm.vue
  assets/app/vue/components/SelfServeForm.vue
  assets/app/vue/components/SignUpFlowForm.vue
  templates/mail/self-serve/connection-info.html
  test/e2e/.env.dev.example
  test/e2e/.env.stage.example
  test/e2e/README.md
  test/e2e/const/constants.ts
  test/e2e/const/types.ts
  test/e2e/pages/email-sign-up-page.ts
  test/e2e/pages/self-serve-page.ts
  test/e2e/playwright.config.ts
  test/e2e/tests/email-sign-up.spec.ts
  test/e2e/tests/self-serve-account-info.spec.ts
  test/e2e/tests/self-serve-connection-info.spec.ts
  test/e2e/tests/sign-in-self-serve.spec.ts
  test/e2e/utils/utils.ts
Labels: testing, M: Mailstrom Front-End Alpha

#82 Add unit test attempting to sign up with non-unique email address
  src/thunderbird_accounts/mail/tests.py
  src/thunderbird_accounts/mail/views.py
Labels: testing
